### ISSUE TITLE
Progress bar not completed when 2 devices selected.

### ISSUE THREAD

**Issue by adashen** [jxtxzzw/vscode-azure-iot-toolkit#8]
1. Select two devices in the web view
2. 10 msg per device
3. interval 1 second
4, dummy json
5. submit

The progress dlg pops up and hang at 50%
The output windows shows:
[2:22:40 PM] Start sending messages from 2 device(s) to IoT Hub.
[2:22:49 PM] All device(s) finished sending in 9.109 second(s).

**Comment by adashen** [comment]
Seems it will happen when the device id including some special char. For example my device is "test#"

**Comment by jxtxzzw** [comment]
Reproduced this problem, but I find the problem still exists even when I use the original `send D2C Message`.
In the end, we find that this issue is caused by SDK, see [azure-iot-sdk-node/issues/288](https://github.com/Azure/azure-iot-sdk-node/issues/288)
