### ISSUE TITLE
simulator Layout issue

### ISSUE THREAD

**Issue by xinyiz1226** [jxtxzzw/vscode-azure-iot-toolkit#9]
when I shrink the window, the layout is strange. we can put the interval into next line for this case:
![image](https://user-images.githubusercontent.com/20178112/63495224-0108e280-c4f2-11e9-8236-2a6cde05419a.png)

**Comment by jxtxzzw** [comment]
Here's the fix `e588877308d9c22e0d368b56bf279ffedb2da95a`:
I set a style with min-width=200px, if the window is narrower than 200px, the interval input will be placed into nextline.
![image](https://user-images.githubusercontent.com/10862845/63497441-52b36c00-c4f6-11e9-8d7d-cc5ef0b53827.png)
